name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Adjust the Node.js version as needed

    - name: Install Dependencies and Build
      run: |
        npm ci
        npm run generate
      env:
        NUXT_APP_BASE_URL: ${{ secrets.NUXT_APP_BASE_URL }}  # Use a GitHub secret for sensitive information

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
