name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.15.0'  # Adjust the Node.js version as needed

    - name: Install Dependencies
      run: |
        yarn install
      env:
        CI: true  # Use the CI environment variable

    - name: Build
      run: |
        yarn build --verbose
      env:
        CI: true  # Use the CI environment variable

    - name: Capture Build Logs
      run: cat /home/runner/work/BlogNuxt/BlogNuxt/.nuxt/analyze/.vite-inspect/*
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        folder: dist
